### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by badVibes--** [ramakarl/voxelizer#1]
Hello, thank you for sharing this!  I wanted to play with it before trying to implement it in my game but I can't seem to compile it.

The errors I get are:

Error C3861 'setdepth3D'   
Error C3861 'checkHit3D'   
Error C3861 'drawCircle3D' 
Error C3861 'drawCircle3D' 
Error C3861 'drawCircle3D' 
Error C3861 'drawCube3D'   
Error C3861 'moveHit3D'    
Error C3861 'moveHit3D'  

These functions are not defined in any of the files :/

**Comment by rob-evercoast** [comment]
Still an issue.

**Comment by Mashpoe** [comment]
same issue, I could not find these functions in the project

**Comment by Amorph** [comment]
This is not an issue at all.
DDA Rasterizer is not usable, it fails on some edge cases, like triangle parallel to some axis.

**Comment by ramakarl** [comment]
The library has been updated to build. Library and voxelizer now build separately. See "How to Build" instructions in the readme. Will reopen if there are still build issues. I'm not sure what @Amorph is talking about. He doesn't provide failing test cases. If rasterizer issues are observed, send me reproduceable vertex positions and I will take a look.
